# build app
FROM  golang:1.26.2-alpine3.23 AS builder
WORKDIR /app
COPY . .
RUN apk add --no-cache make
RUN go mod verify && go mod download
RUN make build-client

# get the binary from the build image to the app image
FROM  golang:1.26.2-alpine3.23
COPY --from=builder /app/bin/client/dfs-cli /bin/dfs-cli
RUN mkdir -p /client_data/manifests /client_data/downloads
ENV MANIFEST_DIR=/client_data/manifests
ENV OUTPUT_DIR=/client_data/downloads
CMD ["tail", "-f", "/dev/null"]
