name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed for buf breaking

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Setup Buf
        uses: bufbuild/buf-setup-action@v1

      # -------- PROTO CHECKS --------

      - name: Check proto formatting
        run: make pb-fmt-check

      - name: Lint proto
        run: make pb-lint

      # skip for now
      # - name: Breaking change check (PR only)
      #   if: github.event_name == 'pull_request'
      #   run: buf breaking --against '.git#branch=main'

      - name: Generate proto code
        run: make proto-gen

      # -------- GO CHECKS --------

      - name: Check Go formatting
        run: make go-fmt-check

      - name: Go Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

      - name: Download Go deps
        run: go mod tidy

      - name: Build
        run: make build-all

      - name: Test
        run: make test-all
